apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory
spec:
  selector:
    matchLabels:
      app: ngsa-memory
  template:
    metadata:
      labels:
        app: ngsa-memory  
    spec:
      containers:
      - name: ds
        imagePullPolicy: Always
        image: ghcr.io/retaildevcrews/ngsa-app:beta
        args:
          - --in-memory
          - --prometheus
          - --log-level
          - Warning
          - --request-log-level
          - Information
          - --zone
          - dev
          - --region
          - dev
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory
spec:
  type: ClusterIP
  selector:
    app: ngsa-memory
  ports:
    - port: 8080
      targetPort: 8080

